name: FoliaPluginTemplate
version: '0.1.0'
main: studio.genbu.mc.foliaplugintemplate.FoliaPluginTemplate
description: Plugin description here.
author: Author
website: http://example.com/
api-version: '1.20.6'
